### PR TITLE
Minimal shims for addEventListener, removeEventListener, dispatchEvent

### PR DESCRIPTION
**Pull request by evnp**
These shims have allowed us to recreate the vast majority of UI scenarios in our [panel](https://github.com/mixpanel/panel) apps with code that's easy to debug and reason about (like the rest of this lib). Chose not to implement bubbling/propagation and related methods for simplicity - event flow in our apps feels more explicit if we don't rely on these mechanisms - but this would be easily attainable if desired.

### CODE REVIEW

**Comment by 1N50MN14** [comment]
hey @evnp thank you for the PR, and also for tidying the code a bit, it's incredible someone actually found this small module useful and even more so everyone that touched on and contributed to it over the past 6 years!

Mind bumping version and updating README to reflect the three new shims, will then merge and npm publish in one go. Cheers to tdumitrescu and the rest of the folks as mixpanel.

**Comment by evnp** [comment]
Thanks for the response @1N50MN14 and for taking a look! This module is fantastic and I greatly appreciate the work people have put into it - UI testing is a never-ending struggle and the simplicity and straightforwardness of this code has been a breath of fresh air.

I put this up speculatively to see if there was interest, if you're open to merging that's great. In that case I added some tests (and some adjustments to the code that were revealed by them). Bumped the version as well and updated readme, let me know if any other additions are needed.

**Comment by 1N50MN14** [comment]
Merged and published, thanks for the PR @evnp! PS took a quick look at panels - *that* looks like a  breath of fresh air :)

**Comment by evnp** [comment]
Thanks @1N50MN14! really appreciate the support, nothing more satisfying then ripping hax out of your codebase because a legit solution has been merged upstream. You should definitely check out panel, it's a sort of minimalist react without all the baggage. Plus webcomponents/shadowdom, 🎉  native tools. We've been using it at Mixpanel for about 3 years to build increasingly complex apps, the simplicity has served us well (and of course shoutout to @tdumitrescu the author).

**Pull request merged**
