### PR TITLE
Added nodeValue for Element, Text and Comment.

### PR DESCRIPTION
**Pull request by ciscoheat**
I needed this, so here you go. :) Specification: https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-F68D080

### CODE REVIEW

**Comment by 1N50MN14** [comment]
jättebra :+1: merged!

**Comment by ciscoheat** [comment]
Inga problem. :) Any chance of an npm update too? Then I can release some stuff depending on this library...

**Comment by 1N50MN14** [comment]
Yup, will do that tomorrow during the day when I'm on my machine & let you know :)

**Comment by 1N50MN14** [comment]
published ;)

**Comment by ciscoheat** [comment]
Thank you very much!

**Pull request merged**
